# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 786, 210))
        self.layoutWidget.setObjectName("layoutWidget")
        self.main_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.project_layout = QtWidgets.QVBoxLayout()
        self.project_layout.setObjectName("project_layout")
        self.dirs_widget = QtWidgets.QTreeWidget(self.layoutWidget)
        self.dirs_widget.setEnabled(True)
        self.dirs_widget.setColumnCount(0)
        self.dirs_widget.setObjectName("dirs_widget")
        self.project_layout.addWidget(self.dirs_widget)
        self.files_widget = QtWidgets.QTreeWidget(self.layoutWidget)
        self.files_widget.setObjectName("files_widget")
        self.files_widget.headerItem().setText(0, "1")
        self.project_layout.addWidget(self.files_widget)
        self.main_layout.addLayout(self.project_layout)
        self.editor_layout = QtWidgets.QVBoxLayout()
        self.editor_layout.setObjectName("editor_layout")
        self.db_layout = QtWidgets.QHBoxLayout()
        self.db_layout.setObjectName("db_layout")
        self.tables = QtWidgets.QTreeWidget(self.layoutWidget)
        self.tables.setObjectName("tables")
        self.tables.headerItem().setText(0, "1")
        self.db_layout.addWidget(self.tables)
        self.table_columns = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_columns.setObjectName("table_columns")
        self.table_columns.setColumnCount(0)
        self.table_columns.setRowCount(0)
        self.db_layout.addWidget(self.table_columns)
        self.editor_layout.addLayout(self.db_layout)
        self.tabs = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabs.setObjectName("tabs")
        self.editor_layout.addWidget(self.tabs)
        self.main_layout.addLayout(self.editor_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 861, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSwitch_language = QtWidgets.QMenu(self.menuEdit)
        self.menuSwitch_language.setObjectName("menuSwitch_language")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuTables = QtWidgets.QMenu(self.menubar)
        self.menuTables.setObjectName("menuTables")
        self.menuTable = QtWidgets.QMenu(self.menubar)
        self.menuTable.setObjectName("menuTable")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.new_file = QtWidgets.QAction(MainWindow)
        self.new_file.setObjectName("new_file")
        self.open_file = QtWidgets.QAction(MainWindow)
        self.open_file.setObjectName("open_file")
        self.actionAs = QtWidgets.QAction(MainWindow)
        self.actionAs.setObjectName("actionAs")
        self.save_file = QtWidgets.QAction(MainWindow)
        self.save_file.setObjectName("save_file")
        self.save_as_file = QtWidgets.QAction(MainWindow)
        self.save_as_file.setObjectName("save_as_file")
        self.langAVS = QtWidgets.QAction(MainWindow)
        self.langAVS.setObjectName("langAVS")
        self.actionBatch = QtWidgets.QAction(MainWindow)
        self.actionBatch.setObjectName("actionBatch")
        self.settings_action = QtWidgets.QAction(MainWindow)
        self.settings_action.setObjectName("settings_action")
        self.project_open = QtWidgets.QAction(MainWindow)
        self.project_open.setObjectName("project_open")
        self.project_close = QtWidgets.QAction(MainWindow)
        self.project_close.setObjectName("project_close")
        self.project_hide = QtWidgets.QAction(MainWindow)
        self.project_hide.setObjectName("project_hide")
        self.project_show = QtWidgets.QAction(MainWindow)
        self.project_show.setObjectName("project_show")
        self.db_create = QtWidgets.QAction(MainWindow)
        self.db_create.setObjectName("db_create")
        self.db_remove = QtWidgets.QAction(MainWindow)
        self.db_remove.setObjectName("db_remove")
        self.db_rename = QtWidgets.QAction(MainWindow)
        self.db_rename.setObjectName("db_rename")
        self.new_db = QtWidgets.QAction(MainWindow)
        self.new_db.setObjectName("new_db")
        self.db_new_row = QtWidgets.QAction(MainWindow)
        self.db_new_row.setObjectName("db_new_row")
        self.actionDrop = QtWidgets.QAction(MainWindow)
        self.actionDrop.setObjectName("actionDrop")
        self.db_remove_row = QtWidgets.QAction(MainWindow)
        self.db_remove_row.setObjectName("db_remove_row")
        self.db_add_row = QtWidgets.QAction(MainWindow)
        self.db_add_row.setObjectName("db_add_row")
        self.db_del_row = QtWidgets.QAction(MainWindow)
        self.db_del_row.setObjectName("db_del_row")
        self.menuFile.addAction(self.new_file)
        self.menuFile.addAction(self.new_db)
        self.menuFile.addAction(self.open_file)
        self.menuFile.addAction(self.save_file)
        self.menuFile.addAction(self.save_as_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.settings_action)
        self.menuEdit.addAction(self.menuSwitch_language.menuAction())
        self.menuProject.addAction(self.project_open)
        self.menuProject.addAction(self.project_close)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.project_hide)
        self.menuProject.addAction(self.project_show)
        self.menuTables.addAction(self.db_create)
        self.menuTables.addAction(self.db_remove)
        self.menuTables.addAction(self.db_rename)
        self.menuTable.addAction(self.db_add_row)
        self.menuTable.addAction(self.db_del_row)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuTables.menuAction())
        self.menubar.addAction(self.menuTable.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuSwitch_language.setTitle(_translate("MainWindow", "Switch language"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuTables.setTitle(_translate("MainWindow", "Tables"))
        self.menuTable.setTitle(_translate("MainWindow", "Table"))
        self.new_file.setText(_translate("MainWindow", "New"))
        self.new_file.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.open_file.setText(_translate("MainWindow", "Open"))
        self.open_file.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionAs.setText(_translate("MainWindow", "As..."))
        self.save_file.setText(_translate("MainWindow", "Save"))
        self.save_file.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.save_as_file.setText(_translate("MainWindow", "Save as"))
        self.save_as_file.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.langAVS.setText(_translate("MainWindow", "AVS"))
        self.actionBatch.setText(_translate("MainWindow", "Batch"))
        self.settings_action.setText(_translate("MainWindow", "Settings"))
        self.project_open.setText(_translate("MainWindow", "Open"))
        self.project_close.setText(_translate("MainWindow", "Close"))
        self.project_hide.setText(_translate("MainWindow", "Hide"))
        self.project_show.setText(_translate("MainWindow", "Show"))
        self.db_create.setText(_translate("MainWindow", "Create"))
        self.db_remove.setText(_translate("MainWindow", "Remove"))
        self.db_rename.setText(_translate("MainWindow", "Rename"))
        self.new_db.setText(_translate("MainWindow", "New datebase"))
        self.db_new_row.setText(_translate("MainWindow", "New row"))
        self.actionDrop.setText(_translate("MainWindow", "Drop"))
        self.db_remove_row.setText(_translate("MainWindow", "Remove row"))
        self.db_add_row.setText(_translate("MainWindow", "Add row"))
        self.db_del_row.setText(_translate("MainWindow", "Remove row"))


